services:
  postgres:
    build:
      context: ./0_database
      dockerfile: Dockerfile
    container_name: dda-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dda_db
    ports:
      - "54325:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: